build:created database schema for users
Spawn-Your-Lawn/spawn-your-lawn pull request #2
Opened 2023-06-12 20:22 UTC by epun21403

# Pull Request Template

## Description

Please include a summary of the change and which issue is fixed. Please also include relevant screenshots of the feature if applicable.

Description: 
Added Prisma as a dependency and created the schema for users. 
Added "DATABASE_URL" to env file in the following format example:
[DATABASE_URL="postgresql://johndoe:randompassword@localhost:5432/mydb?schema=public"](postgresql://USER:PASSWORD@HOST:PORT/DATABASE?schema=SCHEMA)
- USER: The name of your database user
- PASSWORD: The password for your database user
-HOST: The name of your host name (for the local environment, it is localhost)
-PORT: The port where your database server is running (typically 5432 for PostgreSQL)
-DATABASE: The name of the [database](https://www.postgresql.org/docs/12/manage-ag-overview.html)
-SCHEMA: The name of the [schema](https://www.postgresql.org/docs/12/ddl-schemas.html) inside the database

I ran the following line in the terminal to create the tables and database:
npx prisma migrate dev --name init

## Type of Change

Please label your pull request as appropriate for the type of change it makes and remove labels that are not relevant below:

- bug: something isn't working
- build: affects the application build process or repository
- documentation: improvements or additions to documentation
- duplicate: this issue or pull request already exists
- enhancement: new feature or request
- good first issue: good for newcomers
- help wanted: extra attention is needed
- invalid: this doesn't seem right
- question: further information is requested
- wontfix: this will not be worked on

## Checklist

- [ ] I have read the [contributing guidelines](CONTRIBUTING.md) for this project.
- [ X] My code follows the code style of this project.
- [ X] If my change requires a change to the documentation, I have updated the documentation accordingly.
- [ ] If applicable, I have added tests to cover my changes.
- [ ] All new and existing tests passed.

## Reviewers

Please tag one or more reviewers who you believe are best suited to review this code.

## Additional Notes

Please add any additional notes or context about this pull request here.

2023-06-12 20:51 UTC, afrodynamic requested changes
Make sure to either delete the `migrations` folder or add it to `.gitignore`, these files don't need to be included in the repo for our usage. The rest LGTM, good work!

```
prisma/migrations/
prisma/migrations/migration_lock.toml
prisma/migrations/20230612195154_init/
prisma/migrations/20230612195154_init/migration.sql
```

2023-06-12 21:09 UTC, afrodynamic approved these changes
LGTM

2023-06-13 01:36 UTC, epun21403 commented
6edd5c0
Added controllers and API routes for users table and favorites table
Added POST for users tables
Added POST, GET, and DELETE for favorites table

2023-06-13 12:57 UTC, afrodynamic requested changes
Left some suggestions to maintain consistency, the rest LGTM

2023-06-13 12:57 UTC, afrodynamic commented on server/controllers/favoritesController.ts
> +  const { plantId } = request.params;
I think we should keep the request format consistent here, the other controller functions are using only using `request.body` so I'd change it here as such:
 
```suggestion
  if (!request.body || !request.body.plantId || !request.body.userId) {
    response.status(500).send("Not all information included");
    return;
  }
```
I'll add an additional suggestion where you reference plantId that'd need to be changed too

2023-06-13 12:57 UTC, afrodynamic commented on server/controllers/favoritesController.ts
> +        plantId: Number(plantId),
As noted above:

```suggestion
        plantId: Number(request.body.plantId),
        
```

2023-06-13 12:57 UTC, afrodynamic commented on server/routes/favoritesRoutes.ts
> +router.delete('/:plantId', removePlantFromFavorite);
For the consistency changes you would want to remove the variable param here too:

```suggestion
router.delete('/', removePlantFromFavorite);
```

2023-06-13 17:52 UTC, epun21403 commented
> Left some suggestions to maintain consistency, the rest LGTM

Implemented recommended changes to maintain consistency.

2023-06-13 18:42 UTC, afrodynamic approved these changes

2023-06-13 18:43 UTC, afrodynamic approved these changes
LGTM

2023-06-13 18:43 UTC, afrodynamic approved these changes

2023-06-14 18:59 UTC, jnovak79 commented on client/src/features/favoritePlants/FavoritePlants.tsx
Line 12, remove console.log

Line 16, remove err from console.log

2023-06-14 19:05 UTC, jnovak79 commented on client/src/features/plantDetails/PlantDetails.tsx
Line 26, remove console.log

line 29 remove error from console.log

2023-06-14 19:09 UTC, jnovak79 requested changes
Some feedback to remove console.logs. Otherwise LGTM

2023-06-14 19:10 UTC, jnovak79 approved these changes
LGTM

2023-06-16 01:26 UTC, afrodynamic approved these changes
LGTM, submitting a commit to update some of the console.logs and return statement logic

2023-06-16 14:12 UTC, merged