init: brought changes over to new repo
Spawn-Your-Lawn/spawn-your-lawn pull request #4
Opened 2023-06-14 14:44 UTC by Sondersong

# Pull Request Template

## Description

Setup boiler plate code for garden grid page, added Cesium dependencies and got the globe working without earth texture loading. Fixed bug with Cesium not mounting and unmounting correctly.

_Lost commit history due to working on wrong repo_

## Type of Change

Please label your pull request as appropriate for the type of change it makes and remove labels that are not relevant below:

- bug: something isn't working
- build: affects the application build process or repository
- documentation: improvements or additions to documentation
- duplicate: this issue or pull request already exists
- **enhancement: new feature or request**
- good first issue: good for newcomers
- help wanted: extra attention is needed
- invalid: this doesn't seem right
- question: further information is requested
- wontfix: this will not be worked on

## Checklist

- [x] I have read the [contributing guidelines](CONTRIBUTING.md) for this project.
- [x] My code follows the code style of this project.
- [x] If my change requires a change to the documentation, I have updated the documentation accordingly.
- [x] If applicable, I have added tests to cover my changes.
- [x] All new and existing tests passed.

## Reviewers

Please tag one or more reviewers who you believe are best suited to review this code.
@afrodynamic 

## Additional Notes

Please add any additional notes or context about this pull request here.

2023-06-16 12:46 UTC, afrodynamic requested changes
LGTM, I'll add a commit addressing the changes I've noted

2023-06-16 12:46 UTC, afrodynamic commented on client/src/features/garden/garden.scss
> +h1 {
Let's remove this style since it's changing all the headers undesirably

2023-06-16 12:46 UTC, afrodynamic commented on client/src/features/garden/Cesium.jsx
> +export class Cesium extends Component {
We would prefer this to be a functional component if possible, will look into it

2023-06-16 14:12 UTC, afrodynamic commented on client/src/features/garden/Cesium.jsx
> +export class Cesium extends Component {
fixed in bd64fdd

2023-06-16 14:13 UTC, afrodynamic commented on client/src/features/garden/garden.scss
> +h1 {
fixed in bd64fdd

2023-06-16 14:19 UTC, jnovak79 approved these changes
LGTM

2023-06-17 00:00 UTC, afrodynamic commented
Merging manually, closing

2023-06-17 00:00 UTC, closed without merging