map feature first draft/help wanted to code review and issue with refresh
Spawn-Your-Lawn/spawn-your-lawn pull request #5
Opened 2023-06-14 18:37 UTC by jnovak79

Added the initial working implementation of the retail search feature. Currently able to search for stores based off of location (City and/or State). However, need to fix issue with the route causing an issue on refresh. 

# Pull Request Template

## Description

Please include a summary of the change and which issue is fixed. Please also include relevant screenshots of the feature if applicable.

## Type of Change

Please label your pull request as appropriate for the type of change it makes and remove labels that are not relevant below:

- bug: something isn't working
- build: affects the application build process or repository
- documentation: improvements or additions to documentation
- duplicate: this issue or pull request already exists
- enhancement: new feature or request
- good first issue: good for newcomers
- help wanted: extra attention is needed
- invalid: this doesn't seem right
- question: further information is requested
- wontfix: this will not be worked on

## Checklist

- [ ] I have read the [contributing guidelines](CONTRIBUTING.md) for this project.
- [ ] My code follows the code style of this project.
- [ ] If my change requires a change to the documentation, I have updated the documentation accordingly.
- [ ] If applicable, I have added tests to cover my changes.
- [ ] All new and existing tests passed.

## Reviewers

Please tag one or more reviewers who you believe are best suited to review this code.

## Additional Notes

Please add any additional notes or context about this pull request here.

2023-06-14 19:18 UTC, epun21403 reviewed
Some change reccommendations

2023-06-14 19:18 UTC, epun21403 commented on server/index.ts
On line 26 do you need err if you are not using it in the console.log on line 27?

2023-06-14 19:18 UTC, epun21403 commented on client/src/components/pages/SellersPage.tsx
On line 70, do you need err if you're not using it in the console.log on line 71?

On line 109, do you need err if you're not using it in the console.log on line 110?

2023-06-14 19:39 UTC, epun21403 commented
Otherwise LGTM 👁 👄 👁

2023-06-16 14:23 UTC, epun21403 reviewed
Maybe needs typescript changes to inputs

2023-06-16 15:40 UTC, afrodynamic requested changes
LGTM, will add a commit to address the comment and add typing/consistency fixes

2023-06-16 16:31 UTC, afrodynamic commented
Closing to fix merge conflict, resolving in new PR

2023-06-16 16:31 UTC, closed without merging